/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "primary-container": "#470054",
        "primary": "#26002d",
        "on-surface-variant": "#4f434e",
        "tertiary-fixed": "#ffdea5",
        "tertiary": "#1a1000",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#e9c176",
        "secondary": "#056970",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#261900",
        "background": "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-fixed": "#35003f",
        "on-primary": "#ffffff",
        "surface-container": "#eeeeee",
        "surface-dim": "#dadada",
        "on-secondary-container": "#106d74",
        "primary-fixed-dim": "#f9acff",
        "inverse-surface": "#2f3131",
        "surface-container-highest": "#e2e2e2",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#ab8944",
        "on-secondary-fixed-variant": "#004f55",
        "surface-container-high": "#e8e8e8",
        "secondary-container": "#9fecf4",
        "outline-variant": "#d2c2cf",
        "on-primary-fixed-variant": "#6c2a77",
        "on-tertiary-fixed-variant": "#5d4201",
        "error": "#ba1a1a",
        "primary-fixed": "#ffd6fe",
        "secondary-fixed": "#a2eff7",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002022",
        "inverse-primary": "#f9acff",
        "surface-tint": "#874391",
        "outline": "#80737f",
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#86d3da",
        "on-primary-container": "#bc73c4",
        "surface-container-low": "#f3f3f3",
        "tertiary-container": "#352400",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
